logging:
  level: INFO
  loggers:
    com.redislabs.university: DEBUG
defaultName: "RediSolar"
redis:
  host: "redis-12392.c270.us-east-1-3.ec2.cloud.redislabs.com"
  port: 12392
  password: "redisru101"
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8081
  adminConnectors:
    - type: http
      port: 8084

